CREATE TABLE IF NOT EXISTS mart.dim_date (
    date_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    year INTEGER NOT NULL UNIQUE,
    CONSTRAINT chk_dim_date_year
        CHECK (year BETWEEN 1960 AND EXTRACT(YEAR FROM CURRENT_DATE))
);
